dist: trusty
sudo: required
language: node_js
node_js:
  - "8.9.0"
cache:
  yarn: true
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "dylanaubrey-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $SONAR_PR_ANALYSIS_TOKEN
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
install:
  - yarn
script:
  - yarn run test
  - sonar-scanner
  - codecov
before_deploy:
  - yarn run compile
deploy:
  provider: script
  script:
    - yarn run publish-cutoff
  skip_cleanup: true
  on:
    tags: true
    branch: master